### ISSUE TITLE
Adjusting text size

### ISSUE THREAD

**Issue by dejiapps** [ashrafDoubleO7/ExpandableSelectionView#8]
Thanks for the great library. Is there any way to adjust the text sizes? I have tried in basic_expandable_item_layout.xml and in basic_expandable_header_layout.xml. However it just stays the same in my app. I can't figure out what I'm missing.

**Comment by dejiapps** [comment]
Nevermind, I figured out what the issue was.

**Comment by AhmedAshrafG** [comment]
@dejiapps hi, can you please point out what the issue was?
